# Generated by Django 5.0.6 on 2025-02-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweat', '0004_remove_city_user_city_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='Citys',
            new_name='city',
        ),
    ]
